"""create bars_cache

Revision ID: 01964fe22575
Revises: 2ab73c58be4b
Create Date: 2026-07-24 23:38:54.008658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01964fe22575'
down_revision: Union[str, Sequence[str], None] = '2ab73c58be4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bars_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'ts', name='uq_bars_cache')
    )
    op.create_index(op.f('ix_bars_cache_symbol'), 'bars_cache', ['symbol'], unique=False)
    op.create_index(op.f('ix_bars_cache_ts'), 'bars_cache', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bars_cache_ts'), table_name='bars_cache')
    op.drop_index(op.f('ix_bars_cache_symbol'), table_name='bars_cache')
    op.drop_table('bars_cache')
    # ### end Alembic commands ###
