"""add stop and trail fields to orders

Revision ID: 30ae5d0fd818
Revises: 3dbdfc2f292e
Create Date: 2026-07-25 00:40:20.958581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ae5d0fd818'
down_revision: Union[str, Sequence[str], None] = '3dbdfc2f292e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_orders', sa.Column('stop_price', sa.Float(), nullable=True))
    op.add_column('trading_orders', sa.Column('trail_amount', sa.Float(), nullable=True))
    op.add_column('trading_orders', sa.Column('trail_high_water', sa.Float(), nullable=True))
    op.alter_column('trading_orders', 'order_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading_orders', 'order_type',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_column('trading_orders', 'trail_high_water')
    op.drop_column('trading_orders', 'trail_amount')
    op.drop_column('trading_orders', 'stop_price')
    # ### end Alembic commands ###
