"""create trading tables

Revision ID: 3dbdfc2f292e
Revises: 01964fe22575
Create Date: 2026-07-25 00:34:12.264940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbdfc2f292e'
down_revision: Union[str, Sequence[str], None] = '01964fe22575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_orders_account_id'), 'trading_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_trading_orders_status'), 'trading_orders', ['status'], unique=False)
    op.create_index(op.f('ix_trading_orders_symbol'), 'trading_orders', ['symbol'], unique=False)
    op.create_table('trading_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_positions_account_id'), 'trading_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_trading_positions_symbol'), 'trading_positions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_positions_symbol'), table_name='trading_positions')
    op.drop_index(op.f('ix_trading_positions_account_id'), table_name='trading_positions')
    op.drop_table('trading_positions')
    op.drop_index(op.f('ix_trading_orders_symbol'), table_name='trading_orders')
    op.drop_index(op.f('ix_trading_orders_status'), table_name='trading_orders')
    op.drop_index(op.f('ix_trading_orders_account_id'), table_name='trading_orders')
    op.drop_table('trading_orders')
    op.drop_table('trading_accounts')
    # ### end Alembic commands ###
